apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataclay-charts.name" . }}-mds
  labels:
    app: mds
    {{- include "dataclay-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mds.replicaCount }}
  selector:
    matchLabels:
      app: mds
      {{- include "dataclay-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml (merge .Values.globalPodAnnotations .Values.mds.podAnnotations) | nindent 8 }}
      labels:
        app: mds
        {{- include "dataclay-charts.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ include "dataclay-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml (merge .Values.globalPodSecurityContext .Values.mds.podSecurityContext) | nindent 8 }}
      containers:
        - name: mds-{{ .Chart.Name }}
          securityContext:
            {{- toYaml (merge .Values.globalSecurityContext .Values.mds.securityContext) | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["python", "-m", "dataclay.metadata"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.mds.service.port }}
              protocol: TCP
          env:
            - name: DATACLAY_KV_HOST
              value: {{ include "dataclay-charts.name" . }}-redis
            - name: DATACLAY_USERNAME
              value: "{{ .Values.dataclayCredentials.username }}"
            - name: DATACLAY_PASSWORD
              value: "{{ .Values.dataclayCredentials.password }}"
            - name: DATACLAY_DATASET
              value: "{{ .Values.dataclayCredentials.dataset }}"
          resources:
            {{- toYaml .Values.mds.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml (merge .Values.globalNodeSelector .Values.mds.nodeSelector) | nindent 8 }}
      affinity:
        {{- toYaml (merge .Values.globalAffinity .Values.mds.affinity) | nindent 8 }}
      tolerations: 
        {{- concat .Values.globalTolerations .Values.mds.tolerations | default (list) | uniq | toYaml | nindent 8 }}
