{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataclay-charts.name" . }}-proxy
  labels:
    app: proxy
    {{- include "dataclay-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: proxy
    {{- include "dataclay-charts.selectorLabels" . | nindent 4 }}
{{- end}}
