apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataclay-charts.name" . }}-redis
  labels:
    app: redis
    {{- include "dataclay-charts.labels" . | nindent 4 }}
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis
